version: '3.8'
name: 'fileferry'
services:
  ff-server:
    build:
        context: ./server
        dockerfile: Dockerfile
    image: fileferry-server
    container_name: fileferry-server
    command: /usr/api/node_modules/.bin/nodemon server.js
    volumes:
      - ./server/:/usr/api
      - ./server/node_modules/:/usr/api/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - ff-db
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      ff-network:
        aliases:
          - ff-server
  ff-db:
    image: mongo
    container_name: fileferry-db
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      ff-network:
        aliases:
          - ff-db
  ff-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: fileferry-client
    container_name: fileferry-client
    command: npm start
    volumes:
      - ./client/:/usr/app
      - ./client/node_modules/:/usr/app/node_modules
      - ./client/public/:/usr/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true # enable hot reloading
    depends_on:
      - ff-server
    ports:
      - "3000:3000"
    networks:
      ff-network:
        aliases:
          - ff-client

networks:
  ff-network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"

volumes:
  data-volume:
  node_modules:
